// Ai AI Service — generated by NC

service "ai"
version "1.0.0"

// AI configuration
set ai_model to "default"
set max_context to 4096
set temperature to 0.7

// Chat with AI
to chat with message:
    if message is empty:
        respond with error "Message cannot be empty"
    ask AI message
    set response to AI said
    set entry to create_entry(message, response)
    save entry to "conversations.json"
    respond with response

// Chat with context (conversation history)
to chat_with_context with session_id and message:
    set history to load("conversations.json", session_id)
    set context to format_context(history)
    set prompt to context + "\nUser: " + message
    ask AI prompt
    set response to AI said
    set entry to create_entry(message, response)
    set entry.session_id to session_id
    save entry to "conversations.json"
    respond with response

// Analyze text
to analyze with text:
    ask AI "Analyze the following text and provide key insights:\n" + text
    set analysis to AI said
    respond with analysis

// Summarize content
to summarize with content:
    ask AI "Provide a concise summary of:\n" + content
    set summary to AI said
    respond with summary

// Classify text into categories
to classify with text and categories:
    set prompt to "Classify the following text into one of these categories: "
    set prompt to prompt + join(categories, ", ") + "\nText: " + text
    ask AI prompt
    set category to AI said
    respond with category

// Generate content
to generate_content with topic and style:
    set prompt to "Write a " + style + " about " + topic
    ask AI prompt
    set content to AI said
    respond with content

// Translate text
to translate with text and target_language:
    set prompt to "Translate the following to " + target_language + ":\n" + text
    ask AI prompt
    set translated to AI said
    respond with translated

// Extract entities from text
to extract_entities with text:
    ask AI "Extract all named entities (people, places, organizations) from:\n" + text
    set entities to AI said
    respond with entities

// Sentiment analysis
to sentiment with text:
    ask AI "Analyze the sentiment of this text (positive/negative/neutral):\n" + text
    set result to AI said
    respond with result

// Content moderation
to moderate with content:
    ask AI "Is this content safe and appropriate? Reply with: safe, warning, or blocked.\n" + content
    set verdict to AI said
    if verdict contains "blocked":
        respond with error "Content blocked by moderation"
    respond with verdict

api:
    POST /ai/chat             runs chat
    POST /ai/chat/context     runs chat_with_context
    POST /ai/analyze          runs analyze
    POST /ai/summarize        runs summarize
    POST /ai/classify         runs classify
    POST /ai/generate         runs generate_content
    POST /ai/translate        runs translate
    POST /ai/entities         runs extract_entities
    POST /ai/sentiment        runs sentiment
    POST /ai/moderate         runs moderate

middleware:
    cors allow all
    rate limit 30 per minute
    auth jwt on /api/*
    log requests to "ai_service.log"
