// Auth Service — generated by NC
// auth

service "auth"
version "1.0.0"

// Authentication
to authenticate with token:
    if token is empty:
        respond with error "No token provided"
    set user to verify_jwt(token)
    if user is empty:
        respond with error "Invalid token"
    respond with user

to login with credentials:
    set username to credentials.username
    set password to credentials.password
    set user to load("users.json", username)
    if user is empty:
        respond with error "User not found"
    if user.password is not password:
        respond with error "Invalid password"
    set token to create_jwt(user)
    respond with token

to register with data:
    set existing to load("users.json", data.username)
    if existing is not empty:
        respond with error "Username taken"
    set data.created_at to now()
    save data to "users.json"
    set token to create_jwt(data)
    respond with token

api:
    POST /auth/login runs login
    POST /auth/register runs register

middleware:
    cors allow all
    rate limit 60 per minute
    auth jwt on /api/*

