// User CRUD Service — generated by NC

service "user_crud"
version "1.0.0"

// Data model for user:
//   id         - unique identifier
//   name       - display name
//   status     - active/inactive
//   created_at - creation timestamp
//   updated_at - last update timestamp

to list_users:
    set items to load("users.json")
    respond with items

to list_users_paginated with page and limit:
    set items to load("users.json")
    set start to (page - 1) * limit
    set result to slice(items, start, limit)
    respond with result

to get_user with id:
    set item to load("users.json", id)
    if item is empty:
        respond with error "User not found"
    respond with item

to create_user with data:
    set data.id to generate_id()
    set data.status to "active"
    set data.created_at to now()
    set data.updated_at to now()
    set items to load("users.json")
    add data to items
    save items to "users.json"
    log "Created user: " + data.id
    respond with data

to update_user with id and data:
    set items to load("users.json")
    set index to find_index(items, id)
    if index is -1:
        respond with error "User not found"
    set data.id to id
    set data.updated_at to now()
    set items[index] to data
    save items to "users.json"
    log "Updated user: " + id
    respond with data

to patch_user with id and fields:
    set items to load("users.json")
    set index to find_index(items, id)
    if index is -1:
        respond with error "User not found"
    set item to items[index]
    merge fields into item
    set item.updated_at to now()
    set items[index] to item
    save items to "users.json"
    respond with item

to delete_user with id:
    set items to load("users.json")
    set index to find_index(items, id)
    if index is -1:
        respond with error "User not found"
    set deleted to items[index]
    remove items[index]
    save items to "users.json"
    log "Deleted user: " + id
    respond with deleted

to count_users:
    set items to load("users.json")
    set total to length(items)
    respond with total

to search_users with query:
    set items to load("users.json")
    set results to filter(items, query)
    respond with results

api:
    GET    /users           runs list_users
    GET    /users/count     runs count_users
    GET    /users/search    runs search_users
    GET    /users/:id       runs get_user
    POST   /users           runs create_user
    PUT    /users/:id       runs update_user
    PATCH  /users/:id       runs patch_user
    DELETE /users/:id       runs delete_user

middleware:
    cors allow all
    rate limit 120 per minute
    log requests to "crud.log"
