apiVersion: v1
kind: Service
metadata:
  name: nc-service
  namespace: nc-lang
  labels:
    app: nc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: nc
