// SwarmOps Setup Wizard — Run: NC_ALLOW_EXEC=1 nc run scripts/setup.nc -b setup

to setup:
    show ""
    show "╔════════════════════════════════════════════╗"
    show "║   SwarmOps Setup Wizard                    ║"
    show "║   by DevHeal Labs AI                       ║"
    show "╚════════════════════════════════════════════╝"
    show ""

    // AI URL (required)
    show "1. AI Provider URL (required)"
    show "   Just the base URL — NC auto-detects the API path"
    show ""
    set ai_url to input("   AI Provider URL: ")
    show ""

    // AI Key (required)
    show "2. API Key (required)"
    show ""
    set api_key to input("   API Key: ")
    show ""

    // AI Model
    show "3. Model name (press Enter for gpt-4o-mini)"
    set ai_model to input("   Model: ")
    if len(ai_model) is equal 0:
        set ai_model to "gpt-4o-mini"
    show ""

    // Optional: Prometheus
    show "4. Prometheus URL (optional — press Enter to skip)"
    set prom_url to input("   Prometheus URL: ")
    show ""

    // Optional: Elasticsearch
    show "5. Elasticsearch URL (optional — press Enter to skip)"
    set es_url to input("   Elasticsearch URL: ")
    show ""

    // Optional: GitHub
    show "6. GitHub Token (optional — press Enter to skip)"
    set gh_token to input("   GitHub Token: ")
    set gh_repo to ""
    if len(gh_token) is above 0:
        set gh_repo to input("   GitHub Repo (org/repo): ")
    show ""

    // Optional: Slack
    show "7. Slack Webhook URL (optional — press Enter to skip)"
    set slack_url to input("   Slack Webhook: ")
    show ""

    // Optional: Monitor URLs
    show "8. Health check URLs to monitor (optional — press Enter to skip)"
    set monitor_urls to input("   Monitor URLs (comma-separated): ")
    show ""

    // Self-heal secret
    show "9. Self-heal secret (protects /self-heal and /rollback)"
    show "   Press Enter to auto-generate one"
    set heal_secret to input("   Secret: ")
    if len(heal_secret) is equal 0:
        set heal_secret to "swarmops-" + str(floor(random() * 99999))
        show "   Generated: " + heal_secret
    show ""

    // Write .env
    set config to "# SwarmOps Configuration (generated by setup wizard)\n"
    set config to config + "NC_AI_URL=" + ai_url + "\n"
    set config to config + "NC_AI_KEY=" + api_key + "\n"
    set config to config + "NC_AI_MODEL=" + ai_model + "\n"
    set config to config + "NC_ALLOW_EXEC=1\n"
    set config to config + "NC_PORT=9090\n"
    set config to config + "HEAL_SECRET=" + heal_secret + "\n"

    if len(prom_url) is above 0:
        set config to config + "PROMETHEUS_URL=" + prom_url + "\n"

    if len(es_url) is above 0:
        set config to config + "ELASTICSEARCH_URL=" + es_url + "\n"

    if len(gh_token) is above 0:
        set config to config + "GITHUB_TOKEN=" + gh_token + "\n"
        set config to config + "GITHUB_REPO=" + gh_repo + "\n"

    if len(slack_url) is above 0:
        set config to config + "SLACK_WEBHOOK=" + slack_url + "\n"

    if len(monitor_urls) is above 0:
        set config to config + "MONITOR_URLS=" + monitor_urls + "\n"

    shell("mkdir -p config incidents")
    write_file("config/.env", config)

    show "════════════════════════════════════════════"
    show "Setup complete! Config saved to config/.env"
    show ""
    show "Configured:"
    show "  AI URL:         " + ai_url
    show "  AI Model:       " + ai_model
    if len(prom_url) is above 0:
        show "  Prometheus:     " + prom_url
    if len(es_url) is above 0:
        show "  Elasticsearch:  " + es_url
    if len(gh_token) is above 0:
        show "  GitHub:         " + gh_repo
    if len(slack_url) is above 0:
        show "  Slack:          configured"
    if len(monitor_urls) is above 0:
        show "  Monitoring:     " + monitor_urls
    show ""
    show "Next: Start SwarmOps with:"
    show "  make serve"
    show ""
    show "Dashboard: http://localhost:9090"
    show ""
