#!/usr/bin/env python3
"""
NC Instruction-Tuning Training Data Generator
==============================================
Generates 250+ complete NC project files in instruction format.
Each file = one training example:
  <|begin|>
  // Description: [natural language prompt]
  // Type: full app
  service "[name]"
  ... complete nc-lang backend ...
  // === NC_FILE_SEPARATOR ===
  page "[Page Name]"
  ... complete nc-ui frontend ...
  // === NC_AGENT_SEPARATOR ===
  service "[name]-agent"
  ... nc-ai agent behaviors ...
  <|end|>

Usage:
  python3 generate_training_data.py
  # Writes to: nc-lang/engine/training_corpus/instruction-pairs/
"""

import os
import re

OUT_DIR = os.path.join(
    os.path.dirname(__file__),
    "..", "engine", "training_corpus", "instruction-pairs"
)


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def title(name):
    return " ".join(w.capitalize() for w in name.replace("-", " ").split())


def backend(name, description, behaviors, routes, features=None):
    """Generate a nc-lang backend service."""
    feat = features or []
    lines = [
        f'<|begin|>',
        f'// Description: {description}',
        f'// Type: full app',
        f'service "{slug(name)}"',
        f'version "1.0.0"',
        '',
    ]
    if "auth" in feat:
        lines += [
            'middleware auth_check:',
            '    set token to request.headers.authorization',
            '    if token is empty:',
            '        respond with error "Unauthorized" status 401',
            '    set user to verify_token(token)',
            '    if user is empty:',
            '        respond with error "Invalid token" status 401',
            '',
        ]
    if "rate_limit" in feat:
        lines += [
            'configure:',
            '    rate_limit is 100',
            '    port is 8080',
            '',
        ]
    lines += behaviors
    lines += ['api:']
    lines += [f'    {r}' for r in routes]
    lines += ['    GET /health runs health_check', '']
    lines += [
        'to health check:',
        f'    respond with {{"status": "ok", "service": "{slug(name)}"}}',
    ]
    return '\n'.join(lines)


def frontend(name, page_title, sections, theme_lines=None):
    """Generate a nc-ui frontend page."""
    theme = theme_lines or [
        'theme:',
        '    primary is "#2563eb"',
        '    background is "#f8fafc"',
        '    font is "Inter, sans-serif"',
        '',
    ]
    lines = [
        f'page "{page_title}"',
        f'title "{page_title} | NC App"',
        '',
    ]
    lines += theme
    lines += sections
    return '\n'.join(lines)


def agent(name, description, behaviors=None):
    """Generate a nc-ai agent."""
    bh = behaviors or []
    lines = [
        f'// {title(name)} AI Agent',
        f'service "{slug(name)}-agent"',
        'version "1.0.0"',
        '',
        'configure:',
        '    max_tokens is 512',
        '    temperature is 0.7',
        '',
    ]
    lines += bh
    lines += [
        'to handle with prompt:',
        f'    purpose: "Handle user request for {name}"',
        f'    ask AI to "You are a helpful {name} assistant. {{{{prompt}}}}" save as response',
        '    respond with {"reply": response}',
        '',
        'to classify with input:',
        '    ask AI to "Classify as: create, read, update, delete, help. Input: {{input}}" save as intent',
        '    respond with {"intent": intent}',
        '',
        'api:',
        '    POST /agent          runs handle',
        '    POST /agent/classify  runs classify',
        '    GET  /agent/health    runs health_check',
        '',
        'to health check:',
        '    respond with {"status": "ok", "ai": "local"}',
    ]
    return '\n'.join(lines)


def project(name, description, back_behaviors, back_routes, front_sections, agent_behaviors=None, features=None, theme_lines=None):
    """Combine backend + frontend + agent into one training file."""
    back = backend(name, description, back_behaviors, back_routes, features)
    front = frontend(name, title(name), front_sections, theme_lines)
    agt = agent(name, description, agent_behaviors)
    return f"{back}\n\n// === NC_FILE_SEPARATOR ===\n\n{front}\n\n// === NC_AGENT_SEPARATOR ===\n\n{agt}\n<|end|>\n"


# ─────────────────────────────────────────────
#  Project definitions
# ─────────────────────────────────────────────

PROJECTS = []


def add(name, description, back_behaviors, back_routes, front_sections, agent_behaviors=None, features=None, theme_lines=None):
    PROJECTS.append({
        "name": name,
        "description": description,
        "back_behaviors": back_behaviors,
        "back_routes": back_routes,
        "front_sections": front_sections,
        "agent_behaviors": agent_behaviors or [],
        "features": features or [],
        "theme_lines": theme_lines,
    })


# ── 1. Todo App ──────────────────────────────
add(
    "todo",
    "a todo app with task management and AI assistance",
    [
        "to list tasks:",
        '    set tasks to load("tasks.json")',
        "    respond with tasks",
        "",
        "to create task with data:",
        "    set data.id to generate_id()",
        '    set data.status to "pending"',
        "    set data.created_at to now()",
        '    set tasks to load("tasks.json")',
        "    add data to tasks",
        '    save tasks to "tasks.json"',
        "    respond with data",
        "",
        "to complete task with id:",
        '    set tasks to load("tasks.json")',
        "    set index to find_index(tasks, id)",
        "    if index is -1:",
        '        respond with error "Task not found"',
        '    set tasks[index].status to "done"',
        "    set tasks[index].completed_at to now()",
        '    save tasks to "tasks.json"',
        "    respond with tasks[index]",
        "",
        "to delete task with id:",
        '    set tasks to load("tasks.json")',
        "    set index to find_index(tasks, id)",
        "    set removed to tasks[index]",
        "    remove removed from tasks",
        '    save tasks to "tasks.json"',
        "    respond with removed",
        "",
    ],
    ["GET /tasks runs list_tasks", "POST /tasks runs create_task",
     "PUT /tasks/:id/complete runs complete_task", "DELETE /tasks/:id runs delete_task"],
    [
        'nav:',
        '    brand "Todo App"',
        '    link "Tasks" to "/tasks"',
        '',
        'section "hero":',
        '    heading "My Tasks"',
        '    text "Stay organized with AI-powered task management"',
        '    button "Add Task" action "createTask" style primary',
        '',
        'section "task-list":',
        '    list from "/tasks" as tasks:',
        '        card:',
        '            heading tasks.title',
        '            text tasks.status',
        '            button "Complete" action "completeTask" style success',
        '            button "Delete" action "deleteTask" style danger',
        '',
        'section "add-task":',
        '    form action "/tasks" method POST:',
        '        input "title" placeholder "What needs to be done?"',
        '        input "description" placeholder "Details..."',
        '        button "Add Task" type submit style primary',
    ],
    [
        'to suggest tasks with context:',
        '    ask AI to "Suggest 5 tasks based on: {{context}}" save as suggestions',
        '    respond with {"suggestions": suggestions}',
        '',
        'to prioritize with tasks:',
        '    ask AI to "Prioritize these tasks by urgency: {{tasks}}" save as ordered',
        '    respond with {"ordered": ordered}',
        '',
    ],
    ["auth"],
)


# ── 2. Blog / CMS ───────────────────────────
add(
    "blog",
    "a blog with posts, comments, and AI content generation",
    [
        "to list posts:",
        '    set posts to load("posts.json")',
        "    respond with posts",
        "",
        "to get post with id:",
        '    set post to load("posts.json", id)',
        "    if post is empty:",
        '        respond with error "Post not found" status 404',
        "    respond with post",
        "",
        "to create post with data:",
        "    set data.id to generate_id()",
        "    set data.created_at to now()",
        '    set data.published to false',
        '    set posts to load("posts.json")',
        "    add data to posts",
        '    save posts to "posts.json"',
        "    respond with data",
        "",
        "to publish post with id:",
        '    set posts to load("posts.json")',
        "    set index to find_index(posts, id)",
        '    set posts[index].published to true',
        "    set posts[index].published_at to now()",
        '    save posts to "posts.json"',
        "    respond with posts[index]",
        "",
        "to add comment with post_id and data:",
        "    set data.id to generate_id()",
        "    set data.post_id to post_id",
        "    set data.created_at to now()",
        '    set comments to load("comments.json")',
        "    add data to comments",
        '    save comments to "comments.json"',
        "    respond with data",
        "",
    ],
    ["GET /posts runs list_posts", "GET /posts/:id runs get_post",
     "POST /posts runs create_post", "PUT /posts/:id/publish runs publish_post",
     "POST /posts/:id/comments runs add_comment"],
    [
        'nav:',
        '    brand "My Blog"',
        '    link "Posts" to "/posts"',
        '    link "Write" to "/editor"',
        '',
        'section "hero":',
        '    heading "Welcome to My Blog"',
        '    text "Thoughts, stories, and ideas"',
        '',
        'section "posts":',
        '    grid from "/posts" as posts columns 3:',
        '        card:',
        '            image posts.cover',
        '            heading posts.title',
        '            text posts.excerpt',
        '            badge posts.published "Published" "Draft"',
        '            link "Read More" to "/posts/{{posts.id}}"',
        '',
        'section "editor":',
        '    form action "/posts" method POST:',
        '        input "title" placeholder "Post title"',
        '        input "excerpt" placeholder "Short description"',
        '        input "content" type textarea placeholder "Write your post..."',
        '        button "Save Draft" type submit style secondary',
        '        button "AI Generate" action "aiGenerate" style primary',
    ],
    [
        'to generate content with topic:',
        '    ask AI to "Write a blog post about: {{topic}}. Include intro, body, conclusion." save as content',
        '    respond with {"content": content}',
        '',
        'to improve writing with text:',
        '    ask AI to "Improve this blog post for clarity and engagement: {{text}}" save as improved',
        '    respond with {"improved": improved}',
        '',
        'to generate seo with post:',
        '    ask AI to "Generate SEO title and meta description for: {{post.title}} — {{post.excerpt}}" save as seo',
        '    respond with {"seo": seo}',
        '',
    ],
    ["auth"],
)


# ── 3. E-commerce ───────────────────────────
add(
    "ecommerce",
    "an e-commerce store with products, cart, and orders",
    [
        "to list products:",
        '    set products to load("products.json")',
        "    respond with products",
        "",
        "to get product with id:",
        '    set product to load("products.json", id)',
        "    respond with product",
        "",
        "to add to cart with user_id and product_id and quantity:",
        '    set cart to load("cart.json", user_id)',
        "    if cart is empty:",
        "        set cart to {\"user_id\": user_id, \"items\": []}",
        "    set item to {\"product_id\": product_id, \"quantity\": quantity}",
        "    add item to cart.items",
        '    save cart to "cart.json"',
        "    respond with cart",
        "",
        "to checkout with user_id:",
        '    set cart to load("cart.json", user_id)',
        "    set order to {\"id\": generate_id(), \"user_id\": user_id, \"items\": cart.items, \"status\": \"pending\", \"created_at\": now()}",
        '    set orders to load("orders.json")',
        "    add order to orders",
        '    save orders to "orders.json"',
        "    respond with order",
        "",
        "to list orders with user_id:",
        '    set orders to load("orders.json")',
        "    set user_orders to filter(orders, \"user_id\", user_id)",
        "    respond with user_orders",
        "",
    ],
    ["GET /products runs list_products", "GET /products/:id runs get_product",
     "POST /cart runs add_to_cart", "POST /checkout runs checkout",
     "GET /orders runs list_orders"],
    [
        'nav:',
        '    brand "Shop"',
        '    link "Products" to "/products"',
        '    link "Cart" to "/cart" icon "cart"',
        '    link "Orders" to "/orders"',
        '',
        'section "products":',
        '    heading "Our Products"',
        '    grid from "/products" as products columns 4:',
        '        card:',
        '            image products.image',
        '            heading products.name',
        '            text products.price style price',
        '            button "Add to Cart" action "addToCart" style primary',
        '',
        'section "cart":',
        '    heading "Your Cart"',
        '    list from "/cart" as items:',
        '        card:',
        '            text items.name',
        '            text items.quantity',
        '            text items.price',
        '    button "Checkout" action "checkout" style primary',
    ],
    [
        'to recommend with user_id:',
        '    set history to load("orders.json", user_id)',
        '    ask AI to "Recommend products for a customer who bought: {{history}}" save as recommendations',
        '    respond with {"recommendations": recommendations}',
        '',
        'to answer product question with question and product_id:',
        '    set product to load("products.json", product_id)',
        '    ask AI to "Answer this product question: {{question}}. Product info: {{product}}" save as answer',
        '    respond with {"answer": answer}',
        '',
    ],
    ["auth"],
)


# ── 4. Chatbot ──────────────────────────────
add(
    "chatbot",
    "an AI chatbot with conversation memory and context",
    [
        "to chat with message and session_id:",
        '    set mem to memory_new(20)',
        '    set history to memory_load(session_id)',
        "    if history is not empty:",
        "        set mem to history",
        "    memory_add(mem, \"user\", message)",
        '    set context to memory_summary(mem)',
        '    ask AI to "You are a helpful assistant. History: {{context}}\\nUser: {{message}}" save as reply',
        '    memory_add(mem, "assistant", reply)',
        "    memory_save(session_id, mem)",
        "    respond with {\"reply\": reply, \"session\": session_id}",
        "",
        "to clear session with session_id:",
        "    memory_clear(session_id)",
        '    respond with {"cleared": true}',
        "",
    ],
    ["POST /chat runs chat", "DELETE /sessions/:id runs clear_session"],
    [
        'section "chat":',
        '    heading "AI Assistant"',
        '    text "Ask me anything. I remember our conversation."',
        '',
        'section "messages":',
        '    list as messages:',
        '        card:',
        '            text messages.role style badge',
        '            text messages.content',
        '',
        'section "input":',
        '    form action "/chat" method POST:',
        '        input "message" placeholder "Type your message..."',
        '        button "Send" type submit style primary',
        '    button "Clear Chat" action "clearSession" style secondary',
    ],
    [
        'to smart reply with message and persona:',
        '    ask AI to "Reply as {{persona}}. Message: {{message}}" save as reply',
        '    respond with {"reply": reply}',
        '',
    ],
)


# ── 5. Auth / Users ─────────────────────────
add(
    "auth",
    "a user authentication system with registration, login, and profile management",
    [
        "to register with email and password and name:",
        '    set users to load("users.json")',
        "    set existing to find_by(users, \"email\", email)",
        "    if existing is not empty:",
        '        respond with error "Email already registered" status 409',
        "    set user to {\"id\": generate_id(), \"email\": email, \"name\": name, \"password\": hash(password), \"created_at\": now()}",
        "    add user to users",
        '    save users to "users.json"',
        "    set token to create_token(user.id)",
        "    respond with {\"user\": user, \"token\": token}",
        "",
        "to login with email and password:",
        '    set users to load("users.json")',
        "    set user to find_by(users, \"email\", email)",
        "    if user is empty:",
        '        respond with error "Invalid credentials" status 401',
        "    if verify_password(password, user.password) is false:",
        '        respond with error "Invalid credentials" status 401',
        "    set token to create_token(user.id)",
        "    respond with {\"user\": user, \"token\": token}",
        "",
        "to get profile with user_id:",
        '    set users to load("users.json")',
        "    set user to find_by(users, \"id\", user_id)",
        "    if user is empty:",
        '        respond with error "User not found" status 404',
        "    respond with user",
        "",
        "to update profile with user_id and data:",
        '    set users to load("users.json")',
        "    set index to find_index(users, user_id)",
        "    merge data into users[index]",
        "    set users[index].updated_at to now()",
        '    save users to "users.json"',
        "    respond with users[index]",
        "",
    ],
    ["POST /register runs register", "POST /login runs login",
     "GET /profile/:id runs get_profile", "PUT /profile/:id runs update_profile"],
    [
        'section "auth":',
        '    tabs:',
        '        tab "Login":',
        '            form action "/login" method POST:',
        '                input "email" type email placeholder "Email address"',
        '                input "password" type password placeholder "Password"',
        '                button "Login" type submit style primary',
        '        tab "Register":',
        '            form action "/register" method POST:',
        '                input "name" placeholder "Full name"',
        '                input "email" type email placeholder "Email address"',
        '                input "password" type password placeholder "Password"',
        '                button "Create Account" type submit style primary',
        '',
        'section "profile":',
        '    card:',
        '        heading "My Profile"',
        '        form action "/profile" method PUT:',
        '            input "name" placeholder "Full name"',
        '            input "email" type email placeholder "Email"',
        '            button "Save Changes" type submit style primary',
    ],
    [
        'to verify identity with token:',
        '    ask AI to "Is this a valid looking JWT token: {{token}}? Reply yes or no." save as valid',
        '    respond with {"valid": valid}',
        '',
    ],
)


# ── 6. Dashboard / Analytics ────────────────
add(
    "dashboard",
    "an analytics dashboard with metrics, charts, and AI insights",
    [
        "to get metrics:",
        '    set data to load("metrics.json")',
        "    respond with data",
        "",
        "to get summary:",
        '    set metrics to load("metrics.json")',
        "    set total to sum(metrics, \"value\")",
        "    set average to avg(metrics, \"value\")",
        "    respond with {\"total\": total, \"average\": average, \"count\": length(metrics)}",
        "",
        "to add metric with data:",
        "    set data.id to generate_id()",
        "    set data.timestamp to now()",
        '    set metrics to load("metrics.json")',
        "    add data to metrics",
        '    save metrics to "metrics.json"',
        "    respond with data",
        "",
        "to get trends with period:",
        '    set metrics to load("metrics.json")',
        "    set filtered to filter_by_period(metrics, period)",
        "    respond with filtered",
        "",
    ],
    ["GET /metrics runs get_metrics", "GET /metrics/summary runs get_summary",
     "POST /metrics runs add_metric", "GET /metrics/trends runs get_trends"],
    [
        'section "header":',
        '    heading "Analytics Dashboard"',
        '    text "Real-time insights for your business"',
        '',
        'section "kpis":',
        '    grid columns 4:',
        '        card:',
        '            heading "Total Users"',
        '            text from "/metrics/summary" as data: data.total',
        '        card:',
        '            heading "Revenue"',
        '            text "$0"',
        '        card:',
        '            heading "Conversions"',
        '            text "0%"',
        '        card:',
        '            heading "Active Sessions"',
        '            text "0"',
        '',
        'section "charts":',
        '    grid columns 2:',
        '        card:',
        '            heading "User Growth"',
        '            text "Chart placeholder"',
        '        card:',
        '            heading "Revenue Trend"',
        '            text "Chart placeholder"',
    ],
    [
        'to analyze trends with data:',
        '    ask AI to "Analyze these metrics and identify trends: {{data}}" save as analysis',
        '    respond with {"analysis": analysis}',
        '',
        'to predict next period with history:',
        '    ask AI to "Based on this historical data, predict next period values: {{history}}" save as prediction',
        '    respond with {"prediction": prediction}',
        '',
        'to generate report with metrics:',
        '    ask AI to "Write an executive summary of these metrics: {{metrics}}" save as report',
        '    respond with {"report": report}',
        '',
    ],
    ["auth"],
)


# ── 7. Enterprise Operations Dashboard ─────
add(
    "ops-center",
    "a multi-tenant operations dashboard with role based access analytics alert center approvals and dark theme",
    [
        "to list_tenants:",
        '    set tenants to load("tenants.json")',
        "    respond with tenants",
        "",
        "to list_roles:",
        '    set roles to load("roles.json")',
        "    respond with roles",
        "",
        "to permission_matrix:",
        '    set matrix to load("permissions.json")',
        "    respond with matrix",
        "",
        "to analytics_overview:",
        '    set metrics to load("metrics.json")',
        "    set pending to length(load(\"approvals.json\"))",
        "    respond with {\"active_tenants\": length(load(\"tenants.json\")), \"pending_approvals\": pending, \"active_alerts\": 3, \"automation_success\": 98, \"metrics\": metrics}",
        "",
        "to list_approvals:",
        '    set approvals to load("approvals.json")',
        "    respond with approvals",
        "",
        "to approve_request with id:",
        '    set approvals to load("approvals.json")',
        "    set index to find_index(approvals, id)",
        '    set approvals[index].status to "approved"',
        '    save approvals to "approvals.json"',
        "    respond with approvals[index]",
        "",
        "to reject_request with id:",
        '    set approvals to load("approvals.json")',
        "    set index to find_index(approvals, id)",
        '    set approvals[index].status to "rejected"',
        '    save approvals to "approvals.json"',
        "    respond with approvals[index]",
        "",
        "to list_alerts:",
        '    set alerts to load("alerts.json")',
        "    respond with alerts",
        "",
    ],
    [
        "GET /api/v1/tenants runs list_tenants",
        "GET /api/v1/roles runs list_roles",
        "GET /api/v1/permissions runs permission_matrix",
        "GET /api/v1/analytics/overview runs analytics_overview",
        "GET /api/v1/approvals runs list_approvals",
        "POST /api/v1/approvals/:id/approve runs approve_request",
        "POST /api/v1/approvals/:id/reject runs reject_request",
        "GET /api/v1/alerts runs list_alerts",
    ],
    [
        'nav:',
        '    brand "Ops Center"',
        '    link "Dashboard" to "/dashboard"',
        '    link "Tenants" to "/tenants"',
        '    link "Roles" to "/roles"',
        '    link "Analytics" to "/analytics"',
        '    link "Approvals" to "/approvals"',
        '    link "Alerts" to "/alerts"',
        '',
        'section "hero":',
        '    heading "Ops Center"',
        '    text "Multi-tenant operations control plane"',
        '',
        'section "kpis":',
        '    grid columns 4:',
        '        card:',
        '            heading "Active Tenants"',
        '            text from "/api/v1/analytics/overview" as data: data.active_tenants',
        '        card:',
        '            heading "Pending Approvals"',
        '            text from "/api/v1/analytics/overview" as data: data.pending_approvals',
        '        card:',
        '            heading "Active Alerts"',
        '            text from "/api/v1/analytics/overview" as data: data.active_alerts',
        '        card:',
        '            heading "Automation Success"',
        '            text from "/api/v1/analytics/overview" as data: data.automation_success',
        '',
        'section "roles":',
        '    heading "Role-Based Access"',
        '    list from "/api/v1/roles" as roles:',
        '        card:',
        '            heading roles.name',
        '            text "Permissions managed centrally"',
        '',
        'section "analytics":',
        '    heading "Analytics Overview"',
        '    grid columns 3:',
        '        card:',
        '            heading "Approval SLA"',
        '            text "98% within target"',
        '        card:',
        '            heading "Escalations"',
        '            text "2 active"',
        '        card:',
        '            heading "Throughput"',
        '            text "42 ops/min"',
        '',
        'section "approvals":',
        '    heading "Approval Queue"',
        '    list from "/api/v1/approvals" as approvals:',
        '        card:',
        '            heading approvals.title',
        '            text approvals.status',
        '            button "Approve" action "approveRequest" style primary',
        '            button "Reject" action "rejectRequest" style danger',
        '',
        'section "alerts":',
        '    heading "Alert Center"',
        '    list from "/api/v1/alerts" as alerts:',
        '        card:',
        '            heading alerts.severity',
        '            text alerts.message',
    ],
    [
        'to summarize approvals with approvals:',
        '    ask AI to "Summarize approval risk and blockers: {{approvals}}" save as summary',
        '    respond with {"summary": summary}',
        '',
        'to recommend action with alert:',
        '    ask AI to "Recommend the best next action for this alert: {{alert}}" save as action',
        '    respond with {"action": action}',
        '',
    ],
    ["auth", "rate_limit"],
    [
        'theme:',
        '    primary is "#22d3ee"',
        '    background is "#0a0a0f"',
        '    foreground is "#e0e0e8"',
        '    font is "Inter, sans-serif"',
        '',
    ],
)


# ── 8. File Upload / Storage ─────────────────
add(
    "files",
    "a file upload and storage service with metadata management",
    [
        "to upload file with file and user_id:",
        "    set file_id to generate_id()",
        "    set path to save_file(file, file_id)",
        "    set meta to {\"id\": file_id, \"user_id\": user_id, \"name\": file.name, \"size\": file.size, \"type\": file.type, \"path\": path, \"created_at\": now()}",
        '    set files to load("files.json")',
        "    add meta to files",
        '    save files to "files.json"',
        "    respond with meta",
        "",
        "to list files with user_id:",
        '    set files to load("files.json")',
        "    set user_files to filter(files, \"user_id\", user_id)",
        "    respond with user_files",
        "",
        "to get file with id:",
        '    set files to load("files.json")',
        "    set file to find_by(files, \"id\", id)",
        "    if file is empty:",
        '        respond with error "File not found" status 404',
        "    respond with file",
        "",
        "to delete file with id:",
        '    set files to load("files.json")',
        "    set index to find_index(files, id)",
        "    set removed to files[index]",
        "    delete_file(removed.path)",
        "    remove removed from files",
        '    save files to "files.json"',
        "    respond with {\"deleted\": true}",
        "",
    ],
    ["POST /files runs upload_file", "GET /files runs list_files",
     "GET /files/:id runs get_file", "DELETE /files/:id runs delete_file"],
    [
        'section "upload":',
        '    heading "File Storage"',
        '    form action "/files" method POST enctype multipart:',
        '        input "file" type file accept "*/*"',
        '        button "Upload" type submit style primary',
        '',
        'section "files":',
        '    list from "/files" as files:',
        '        card:',
        '            icon files.type',
        '            text files.name',
        '            text files.size',
        '            link "Download" to "/files/{{files.id}}"',
        '            button "Delete" action "deleteFile" style danger',
    ],
    [
        'to describe file with file_id:',
        '    set file to load("files.json", file_id)',
        '    ask AI to "Describe what this file might contain based on: name={{file.name}}, type={{file.type}}, size={{file.size}}" save as description',
        '    respond with {"description": description}',
        '',
    ],
    ["auth"],
)


# ── 8. Support Tickets ───────────────────────
add(
    "support",
    "a customer support ticket system with AI classification and routing",
    [
        "to create ticket with data:",
        "    set data.id to generate_id()",
        '    set data.status to "open"',
        '    set data.priority to "medium"',
        "    set data.created_at to now()",
        '    set tickets to load("tickets.json")',
        "    add data to tickets",
        '    save tickets to "tickets.json"',
        "    respond with data",
        "",
        "to list tickets:",
        '    set tickets to load("tickets.json")',
        "    respond with tickets",
        "",
        "to get ticket with id:",
        '    set ticket to load("tickets.json", id)',
        "    respond with ticket",
        "",
        "to update ticket with id and data:",
        '    set tickets to load("tickets.json")',
        "    set index to find_index(tickets, id)",
        "    merge data into tickets[index]",
        "    set tickets[index].updated_at to now()",
        '    save tickets to "tickets.json"',
        "    respond with tickets[index]",
        "",
        "to close ticket with id:",
        '    set tickets to load("tickets.json")',
        "    set index to find_index(tickets, id)",
        '    set tickets[index].status to "closed"',
        "    set tickets[index].closed_at to now()",
        '    save tickets to "tickets.json"',
        "    respond with tickets[index]",
        "",
    ],
    ["POST /tickets runs create_ticket", "GET /tickets runs list_tickets",
     "GET /tickets/:id runs get_ticket", "PUT /tickets/:id runs update_ticket",
     "POST /tickets/:id/close runs close_ticket"],
    [
        'section "tickets":',
        '    heading "Support Tickets"',
        '    button "New Ticket" action "openForm" style primary',
        '',
        '    list from "/tickets" as tickets:',
        '        card:',
        '            badge tickets.priority',
        '            heading tickets.title',
        '            text tickets.description',
        '            badge tickets.status',
        '            button "View" action "viewTicket" style secondary',
        '            button "Close" action "closeTicket" style danger',
        '',
        'section "new-ticket":',
        '    form action "/tickets" method POST:',
        '        input "title" placeholder "Issue title"',
        '        input "description" type textarea placeholder "Describe your issue"',
        '        dropdown "priority" options "low,medium,high,critical"',
        '        button "Submit Ticket" type submit style primary',
    ],
    [
        'to classify ticket with ticket:',
        '    ask AI to "Classify this support ticket into: bug, feature, question, billing, security. Title: {{ticket.title}} Description: {{ticket.description}}" save as category',
        '    respond with {"category": category}',
        '',
        'to suggest response with ticket:',
        '    ask AI to "Suggest a helpful response for this support ticket: {{ticket.title}} — {{ticket.description}}" save as suggestion',
        '    respond with {"suggestion": suggestion}',
        '',
        'to set priority with ticket:',
        '    ask AI to "Rate priority as low, medium, high, or critical. Ticket: {{ticket.title}} — {{ticket.description}}" save as priority',
        '    respond with {"priority": priority}',
        '',
    ],
)


# ── 9. Inventory Management ──────────────────
add(
    "inventory",
    "an inventory management system with stock tracking and alerts",
    [
        "to list items:",
        '    set items to load("inventory.json")',
        "    respond with items",
        "",
        "to get item with id:",
        '    set item to load("inventory.json", id)',
        "    respond with item",
        "",
        "to add item with data:",
        "    set data.id to generate_id()",
        "    set data.created_at to now()",
        '    set items to load("inventory.json")',
        "    add data to items",
        '    save items to "inventory.json"',
        "    respond with data",
        "",
        "to update stock with id and quantity:",
        '    set items to load("inventory.json")',
        "    set index to find_index(items, id)",
        "    set items[index].stock to quantity",
        "    set items[index].updated_at to now()",
        '    save items to "inventory.json"',
        "    respond with items[index]",
        "",
        "to low stock alert:",
        '    set items to load("inventory.json")',
        "    set low to filter_by_threshold(items, \"stock\", 10)",
        "    respond with low",
        "",
    ],
    ["GET /inventory runs list_items", "GET /inventory/:id runs get_item",
     "POST /inventory runs add_item", "PUT /inventory/:id/stock runs update_stock",
     "GET /inventory/alerts/low-stock runs low_stock_alert"],
    [
        'section "inventory":',
        '    heading "Inventory Management"',
        '    button "Add Item" action "openAddForm" style primary',
        '',
        '    grid from "/inventory" as items columns 3:',
        '        card:',
        '            image items.image',
        '            heading items.name',
        '            text items.sku style mono',
        '            text items.stock style number',
        '            badge items.stock "In Stock" "Low Stock" threshold 10',
        '            button "Update Stock" action "updateStock" style secondary',
        '',
        'section "alerts":',
        '    heading "Low Stock Alerts"',
        '    list from "/inventory/alerts/low-stock" as low:',
        '        card:',
        '            heading low.name',
        '            text low.stock style danger',
        '            button "Reorder" action "reorder" style primary',
    ],
    [
        'to forecast demand with item_id:',
        '    set history to load("sales.json", item_id)',
        '    ask AI to "Forecast demand for next month based on sales history: {{history}}" save as forecast',
        '    respond with {"forecast": forecast}',
        '',
        'to generate reorder suggestion with low_items:',
        '    ask AI to "Suggest reorder quantities for these low-stock items: {{low_items}}" save as suggestions',
        '    respond with {"suggestions": suggestions}',
        '',
    ],
)


# ── 10. Booking / Scheduling ─────────────────
add(
    "booking",
    "a booking and scheduling system for appointments",
    [
        "to list slots:",
        '    set slots to load("slots.json")',
        "    set available to filter(slots, \"available\", true)",
        "    respond with available",
        "",
        "to book slot with slot_id and user_id and data:",
        '    set slots to load("slots.json")',
        "    set index to find_index(slots, slot_id)",
        "    if slots[index].available is false:",
        '        respond with error "Slot not available" status 409',
        "    set booking to {\"id\": generate_id(), \"slot_id\": slot_id, \"user_id\": user_id, \"status\": \"confirmed\", \"created_at\": now()}",
        "    merge data into booking",
        '    set slots[index].available to false',
        '    save slots to "slots.json"',
        '    set bookings to load("bookings.json")',
        "    add booking to bookings",
        '    save bookings to "bookings.json"',
        "    respond with booking",
        "",
        "to cancel booking with id:",
        '    set bookings to load("bookings.json")',
        "    set index to find_index(bookings, id)",
        "    set slot_id to bookings[index].slot_id",
        '    set bookings[index].status to "cancelled"',
        '    save bookings to "bookings.json"',
        '    set slots to load("slots.json")',
        "    set slot_index to find_index(slots, slot_id)",
        '    set slots[slot_index].available to true',
        '    save slots to "slots.json"',
        '    respond with {"cancelled": true}',
        "",
        "to list my bookings with user_id:",
        '    set bookings to load("bookings.json")',
        "    set my_bookings to filter(bookings, \"user_id\", user_id)",
        "    respond with my_bookings",
        "",
    ],
    ["GET /slots runs list_slots", "POST /bookings runs book_slot",
     "DELETE /bookings/:id runs cancel_booking", "GET /bookings/my runs list_my_bookings"],
    [
        'section "booking":',
        '    heading "Book an Appointment"',
        '    text "Choose a time that works for you"',
        '',
        'section "slots":',
        '    grid from "/slots" as slots columns 4:',
        '        card:',
        '            heading slots.date',
        '            text slots.time',
        '            text slots.duration',
        '            button "Book" action "bookSlot" style primary',
        '',
        'section "my-bookings":',
        '    heading "My Bookings"',
        '    list from "/bookings/my" as bookings:',
        '        card:',
        '            heading bookings.date',
        '            text bookings.time',
        '            badge bookings.status',
        '            button "Cancel" action "cancelBooking" style danger',
    ],
    [
        'to suggest best time with preferences:',
        '    ask AI to "Suggest the best appointment time based on preferences: {{preferences}}" save as suggestion',
        '    respond with {"suggestion": suggestion}',
        '',
        'to send reminder with booking:',
        '    ask AI to "Write a friendly appointment reminder for: {{booking.date}} at {{booking.time}}" save as reminder',
        '    respond with {"reminder": reminder}',
        '',
    ],
    ["auth"],
)


# ── 11. Notes App ────────────────────────────
add(
    "notes",
    "a note-taking app with AI summarization and search",
    [
        "to list notes with user_id:",
        '    set notes to load("notes.json")',
        "    set my_notes to filter(notes, \"user_id\", user_id)",
        "    respond with my_notes",
        "",
        "to create note with user_id and data:",
        "    set data.id to generate_id()",
        "    set data.user_id to user_id",
        "    set data.created_at to now()",
        '    set notes to load("notes.json")',
        "    add data to notes",
        '    save notes to "notes.json"',
        "    respond with data",
        "",
        "to update note with id and data:",
        '    set notes to load("notes.json")',
        "    set index to find_index(notes, id)",
        "    merge data into notes[index]",
        "    set notes[index].updated_at to now()",
        '    save notes to "notes.json"',
        "    respond with notes[index]",
        "",
        "to delete note with id:",
        '    set notes to load("notes.json")',
        "    set index to find_index(notes, id)",
        "    set removed to notes[index]",
        "    remove removed from notes",
        '    save notes to "notes.json"',
        '    respond with {"deleted": true}',
        "",
        "to search notes with query and user_id:",
        '    set notes to load("notes.json")',
        "    set my_notes to filter(notes, \"user_id\", user_id)",
        "    set results to search(my_notes, query)",
        "    respond with results",
        "",
    ],
    ["GET /notes runs list_notes", "POST /notes runs create_note",
     "PUT /notes/:id runs update_note", "DELETE /notes/:id runs delete_note",
     "GET /notes/search runs search_notes"],
    [
        'section "notes":',
        '    heading "My Notes"',
        '    button "New Note" action "createNote" style primary',
        '    input "search" placeholder "Search notes..." action "searchNotes"',
        '',
        '    grid from "/notes" as notes columns 3:',
        '        card:',
        '            heading notes.title',
        '            text notes.content style truncate',
        '            text notes.updated_at style meta',
        '            button "Edit" action "editNote" style secondary',
        '            button "Delete" action "deleteNote" style danger',
        '            button "AI Summary" action "summarizeNote" style ai',
        '',
        'section "editor":',
        '    form action "/notes" method POST:',
        '        input "title" placeholder "Note title"',
        '        input "content" type textarea placeholder "Start writing..."',
        '        button "Save Note" type submit style primary',
    ],
    [
        'to summarize note with content:',
        '    ask AI to "Summarize this note in 3 bullet points: {{content}}" save as summary',
        '    respond with {"summary": summary}',
        '',
        'to enhance note with content:',
        '    ask AI to "Improve and expand on this note: {{content}}" save as enhanced',
        '    respond with {"enhanced": enhanced}',
        '',
        'to extract action items with content:',
        '    ask AI to "Extract action items from this note: {{content}}" save as actions',
        '    respond with {"actions": actions}',
        '',
    ],
    ["auth"],
)


# ── 12. Job Queue / Worker ────────────────────
add(
    "job-queue",
    "a job queue system with workers, priorities, and status tracking",
    [
        "to enqueue job with data:",
        "    set job to {\"id\": generate_id(), \"status\": \"pending\", \"priority\": data.priority or \"normal\", \"payload\": data.payload, \"created_at\": now(), \"attempts\": 0}",
        '    set jobs to load("jobs.json")',
        "    add job to jobs",
        '    save jobs to "jobs.json"',
        "    respond with job",
        "",
        "to dequeue job:",
        '    set jobs to load("jobs.json")',
        "    set pending to filter(jobs, \"status\", \"pending\")",
        "    if pending is empty:",
        '        respond with {"job": null}',
        "    set job to pending[0]",
        "    set index to find_index(jobs, job.id)",
        '    set jobs[index].status to "processing"',
        "    set jobs[index].started_at to now()",
        '    save jobs to "jobs.json"',
        "    respond with job",
        "",
        "to complete job with id:",
        '    set jobs to load("jobs.json")',
        "    set index to find_index(jobs, id)",
        '    set jobs[index].status to "done"',
        "    set jobs[index].completed_at to now()",
        '    save jobs to "jobs.json"',
        "    respond with jobs[index]",
        "",
        "to fail job with id and error:",
        '    set jobs to load("jobs.json")',
        "    set index to find_index(jobs, id)",
        '    set jobs[index].status to "failed"',
        "    set jobs[index].error to error",
        "    set jobs[index].attempts to jobs[index].attempts + 1",
        '    save jobs to "jobs.json"',
        "    respond with jobs[index]",
        "",
        "to list jobs with status:",
        '    set jobs to load("jobs.json")',
        "    if status is not empty:",
        "        set jobs to filter(jobs, \"status\", status)",
        "    respond with jobs",
        "",
    ],
    ["POST /jobs runs enqueue_job", "GET /jobs/dequeue runs dequeue_job",
     "PUT /jobs/:id/complete runs complete_job", "PUT /jobs/:id/fail runs fail_job",
     "GET /jobs runs list_jobs"],
    [
        'section "queue":',
        '    heading "Job Queue"',
        '',
        '    grid columns 4:',
        '        card:',
        '            heading "Pending"',
        '            text from "/jobs?status=pending" as jobs: jobs.length',
        '        card:',
        '            heading "Processing"',
        '            text from "/jobs?status=processing" as jobs: jobs.length',
        '        card:',
        '            heading "Done"',
        '            text from "/jobs?status=done" as jobs: jobs.length',
        '        card:',
        '            heading "Failed"',
        '            text from "/jobs?status=failed" as jobs: jobs.length',
        '',
        '    list from "/jobs" as jobs:',
        '        card:',
        '            text jobs.id style mono',
        '            badge jobs.status',
        '            badge jobs.priority',
        '            text jobs.created_at style meta',
    ],
    [
        'to analyze job failures with failed_jobs:',
        '    ask AI to "Analyze these failed jobs and suggest fixes: {{failed_jobs}}" save as analysis',
        '    respond with {"analysis": analysis}',
        '',
    ],
)


# ── 13. Voting / Poll System ──────────────────
add(
    "polls",
    "a voting and poll system with real-time results",
    [
        "to create poll with data:",
        "    set data.id to generate_id()",
        "    set data.created_at to now()",
        "    set data.votes to {}",
        '    set polls to load("polls.json")',
        "    add data to polls",
        '    save polls to "polls.json"',
        "    respond with data",
        "",
        "to list polls:",
        '    set polls to load("polls.json")',
        "    respond with polls",
        "",
        "to get poll with id:",
        '    set poll to load("polls.json", id)',
        "    respond with poll",
        "",
        "to vote with poll_id and option and user_id:",
        '    set polls to load("polls.json")',
        "    set index to find_index(polls, poll_id)",
        "    if polls[index].votes[user_id] is not empty:",
        '        respond with error "Already voted" status 409',
        "    set polls[index].votes[user_id] to option",
        '    save polls to "polls.json"',
        "    respond with polls[index]",
        "",
        "to get results with poll_id:",
        '    set poll to load("polls.json", poll_id)',
        "    set results to count_votes(poll.votes)",
        "    respond with results",
        "",
    ],
    ["POST /polls runs create_poll", "GET /polls runs list_polls",
     "GET /polls/:id runs get_poll", "POST /polls/:id/vote runs vote",
     "GET /polls/:id/results runs get_results"],
    [
        'section "polls":',
        '    heading "Polls & Voting"',
        '    button "Create Poll" action "openCreateForm" style primary',
        '',
        '    list from "/polls" as polls:',
        '        card:',
        '            heading polls.question',
        '            list polls.options as option:',
        '                button option action "vote" style option',
        '            link "View Results" to "/polls/{{polls.id}}/results"',
        '',
        'section "create-poll":',
        '    form action "/polls" method POST:',
        '        input "question" placeholder "Ask your question..."',
        '        input "options" placeholder "Option 1, Option 2, Option 3"',
        '        button "Create Poll" type submit style primary',
    ],
    [
        'to generate poll question with topic:',
        '    ask AI to "Generate 5 interesting poll questions about: {{topic}}" save as questions',
        '    respond with {"questions": questions}',
        '',
        'to analyze results with results:',
        '    ask AI to "Analyze these poll results and give insights: {{results}}" save as insights',
        '    respond with {"insights": insights}',
        '',
    ],
)


# ── 14. Notification Service ──────────────────
add(
    "notifications",
    "a notification service with email, push, and in-app notifications",
    [
        "to send notification with user_id and type and message:",
        "    set notif to {\"id\": generate_id(), \"user_id\": user_id, \"type\": type, \"message\": message, \"read\": false, \"created_at\": now()}",
        '    set notifications to load("notifications.json")',
        "    add notif to notifications",
        '    save notifications to "notifications.json"',
        "    if type is \"email\":",
        "        send_email(user_id, message)",
        "    respond with notif",
        "",
        "to list notifications with user_id:",
        '    set notifications to load("notifications.json")',
        "    set my_notifs to filter(notifications, \"user_id\", user_id)",
        "    respond with my_notifs",
        "",
        "to mark read with id:",
        '    set notifications to load("notifications.json")',
        "    set index to find_index(notifications, id)",
        "    set notifications[index].read to true",
        "    set notifications[index].read_at to now()",
        '    save notifications to "notifications.json"',
        "    respond with notifications[index]",
        "",
        "to mark all read with user_id:",
        '    set notifications to load("notifications.json")',
        "    repeat for each notif in notifications:",
        "        if notif.user_id is user_id:",
        "            set notif.read to true",
        '    save notifications to "notifications.json"',
        '    respond with {"marked": true}',
        "",
    ],
    ["POST /notifications runs send_notification", "GET /notifications runs list_notifications",
     "PUT /notifications/:id/read runs mark_read", "PUT /notifications/read-all runs mark_all_read"],
    [
        'section "notifications":',
        '    heading "Notifications"',
        '    button "Mark All Read" action "markAllRead" style secondary',
        '',
        '    list from "/notifications" as notifs:',
        '        card style notifs.read ? "read" : "unread":',
        '            icon notifs.type',
        '            text notifs.message',
        '            text notifs.created_at style meta',
        '            button "Mark Read" action "markRead" style ghost',
    ],
    [
        'to compose notification with context:',
        '    ask AI to "Write a clear, friendly notification message for: {{context}}" save as message',
        '    respond with {"message": message}',
        '',
    ],
)


# ── 15. Recipe / Food App ────────────────────
add(
    "recipes",
    "a recipe app with meal planning and AI ingredient substitution",
    [
        "to list recipes:",
        '    set recipes to load("recipes.json")',
        "    respond with recipes",
        "",
        "to get recipe with id:",
        '    set recipe to load("recipes.json", id)',
        "    respond with recipe",
        "",
        "to create recipe with data:",
        "    set data.id to generate_id()",
        "    set data.created_at to now()",
        '    set recipes to load("recipes.json")',
        "    add data to recipes",
        '    save recipes to "recipes.json"',
        "    respond with data",
        "",
        "to search recipes with query:",
        '    set recipes to load("recipes.json")',
        "    set results to search(recipes, query)",
        "    respond with results",
        "",
        "to list by ingredient with ingredient:",
        '    set recipes to load("recipes.json")',
        "    set matching to filter_contains(recipes, \"ingredients\", ingredient)",
        "    respond with matching",
        "",
    ],
    ["GET /recipes runs list_recipes", "GET /recipes/:id runs get_recipe",
     "POST /recipes runs create_recipe", "GET /recipes/search runs search_recipes",
     "GET /recipes/by-ingredient runs list_by_ingredient"],
    [
        'nav:',
        '    brand "Recipes"',
        '    input "search" placeholder "Search recipes..." action "search"',
        '',
        'section "featured":',
        '    heading "Featured Recipes"',
        '    grid from "/recipes" as recipes columns 3:',
        '        card:',
        '            image recipes.image',
        '            heading recipes.name',
        '            text recipes.prep_time',
        '            text recipes.difficulty',
        '            link "View Recipe" to "/recipes/{{recipes.id}}"',
        '',
        'section "recipe-detail":',
        '    card:',
        '        heading "Ingredients"',
        '        list as ingredients:',
        '            text ingredients',
        '        heading "Instructions"',
        '        list as steps:',
        '            text steps',
        '        button "Get Substitutions" action "getSubstitutions" style ai',
    ],
    [
        'to substitute ingredient with ingredient and dietary:',
        '    ask AI to "Suggest substitutes for {{ingredient}} that are {{dietary}}-friendly" save as substitutes',
        '    respond with {"substitutes": substitutes}',
        '',
        'to generate recipe from ingredients with ingredients:',
        '    ask AI to "Create a recipe using these ingredients: {{ingredients}}" save as recipe',
        '    respond with {"recipe": recipe}',
        '',
        'to scale recipe with recipe and servings:',
        '    ask AI to "Scale this recipe from {{recipe.servings}} to {{servings}} servings: {{recipe.ingredients}}" save as scaled',
        '    respond with {"ingredients": scaled}',
        '',
    ],
)


# ── 16. API Gateway / Proxy ──────────────────
add(
    "api-gateway",
    "an API gateway with routing, rate limiting, and authentication",
    [
        "to proxy request with service and path and method:",
        '    set services to load("services.json")',
        "    set target to find_by(services, \"name\", service)",
        "    if target is empty:",
        '        respond with error "Service not found" status 404',
        "    set response to forward(target.url + path, method)",
        "    respond with response",
        "",
        "to list services:",
        '    set services to load("services.json")',
        "    respond with services",
        "",
        "to register service with data:",
        "    set data.id to generate_id()",
        "    set data.registered_at to now()",
        '    set services to load("services.json")',
        "    add data to services",
        '    save services to "services.json"',
        "    respond with data",
        "",
        "to health check all:",
        '    set services to load("services.json")',
        "    set results to []",
        "    repeat for each service in services:",
        "        set health to ping(service.url + \"/health\")",
        "        set result to {\"service\": service.name, \"status\": health.status}",
        "        add result to results",
        "    respond with results",
        "",
    ],
    ["ANY /:service/:path runs proxy_request", "GET /gateway/services runs list_services",
     "POST /gateway/services runs register_service", "GET /gateway/health runs health_check_all"],
    [
        'section "gateway":',
        '    heading "API Gateway"',
        '    text "Route, secure, and monitor your APIs"',
        '',
        '    grid columns 3:',
        '        card:',
        '            heading "Services"',
        '            text from "/gateway/services" as s: s.length',
        '        card:',
        '            heading "Requests/min"',
        '            text "0"',
        '        card:',
        '            heading "Uptime"',
        '            text "100%"',
        '',
        '    list from "/gateway/services" as services:',
        '        card:',
        '            heading services.name',
        '            text services.url style mono',
        '            badge services.status',
    ],
    [
        'to analyze traffic with logs:',
        '    ask AI to "Analyze this API traffic and identify anomalies: {{logs}}" save as analysis',
        '    respond with {"analysis": analysis}',
        '',
    ],
    ["auth", "rate_limit"],
)


# ── 17. Newsletter / Email ───────────────────
add(
    "newsletter",
    "a newsletter and email marketing service",
    [
        "to subscribe with email and name:",
        '    set subscribers to load("subscribers.json")',
        "    set existing to find_by(subscribers, \"email\", email)",
        "    if existing is not empty:",
        '        respond with error "Already subscribed" status 409',
        "    set subscriber to {\"id\": generate_id(), \"email\": email, \"name\": name, \"subscribed_at\": now(), \"active\": true}",
        "    add subscriber to subscribers",
        '    save subscribers to "subscribers.json"',
        "    respond with subscriber",
        "",
        "to unsubscribe with email:",
        '    set subscribers to load("subscribers.json")',
        "    set index to find_index_by(subscribers, \"email\", email)",
        "    set subscribers[index].active to false",
        '    save subscribers to "subscribers.json"',
        '    respond with {"unsubscribed": true}',
        "",
        "to send campaign with subject and content:",
        '    set subscribers to load("subscribers.json")',
        "    set active to filter(subscribers, \"active\", true)",
        "    repeat for each sub in active:",
        "        send_email(sub.email, subject, content)",
        '    respond with {"sent": length(active)}',
        "",
        "to list subscribers:",
        '    set subscribers to load("subscribers.json")',
        "    respond with subscribers",
        "",
    ],
    ["POST /subscribe runs subscribe", "DELETE /unsubscribe runs unsubscribe",
     "POST /campaign runs send_campaign", "GET /subscribers runs list_subscribers"],
    [
        'section "newsletter":',
        '    heading "Newsletter"',
        '    text "Stay updated with our latest news"',
        '',
        '    form action "/subscribe" method POST:',
        '        input "name" placeholder "Your name"',
        '        input "email" type email placeholder "your@email.com"',
        '        button "Subscribe" type submit style primary',
        '',
        'section "campaigns":',
        '    heading "Send Campaign"',
        '    form action "/campaign" method POST:',
        '        input "subject" placeholder "Email subject"',
        '        input "content" type textarea placeholder "Email content"',
        '        button "Send to All" type submit style primary',
        '        button "AI Generate" action "aiGenerate" style ai',
    ],
    [
        'to generate email with topic:',
        '    ask AI to "Write an engaging newsletter email about: {{topic}}. Include subject line, intro, body, and CTA." save as email',
        '    respond with {"email": email}',
        '',
        'to personalize email with subscriber and template:',
        '    ask AI to "Personalize this email template for {{subscriber.name}}: {{template}}" save as personalized',
        '    respond with {"email": personalized}',
        '',
    ],
)


# ── 18. URL Shortener ────────────────────────
add(
    "url-shortener",
    "a URL shortener service with analytics and custom slugs",
    [
        "to shorten with url and custom_slug:",
        '    set links to load("links.json")',
        "    if custom_slug is not empty:",
        "        set slug to custom_slug",
        "    else:",
        "        set slug to random_string(6)",
        "    set existing to find_by(links, \"slug\", slug)",
        "    if existing is not empty:",
        '        respond with error "Slug taken" status 409',
        "    set link to {\"id\": generate_id(), \"url\": url, \"slug\": slug, \"clicks\": 0, \"created_at\": now()}",
        "    add link to links",
        '    save links to "links.json"',
        "    respond with link",
        "",
        "to redirect with slug:",
        '    set links to load("links.json")',
        "    set link to find_by(links, \"slug\", slug)",
        "    if link is empty:",
        '        respond with error "Link not found" status 404',
        "    set index to find_index(links, link.id)",
        "    set links[index].clicks to links[index].clicks + 1",
        '    save links to "links.json"',
        "    redirect to link.url",
        "",
        "to get stats with slug:",
        '    set links to load("links.json")',
        "    set link to find_by(links, \"slug\", slug)",
        "    respond with link",
        "",
        "to list links:",
        '    set links to load("links.json")',
        "    respond with links",
        "",
    ],
    ["POST /shorten runs shorten", "GET /:slug runs redirect",
     "GET /stats/:slug runs get_stats", "GET /links runs list_links"],
    [
        'section "shorten":',
        '    heading "URL Shortener"',
        '',
        '    form action "/shorten" method POST:',
        '        input "url" type url placeholder "https://your-long-url.com/..."',
        '        input "custom_slug" placeholder "custom-slug (optional)"',
        '        button "Shorten" type submit style primary',
        '',
        'section "links":',
        '    list from "/links" as links:',
        '        card:',
        '            text links.slug style mono',
        '            link links.url to links.url',
        '            text links.clicks style badge',
        '            button "Copy" action "copy" style secondary',
    ],
    [
        'to suggest slug with url:',
        '    ask AI to "Suggest a short memorable slug for this URL: {{url}}. Reply with just the slug, no explanation." save as slug',
        '    respond with {"slug": slug}',
        '',
    ],
)


# ── 19. Survey / Form Builder ────────────────
add(
    "survey",
    "a survey and form builder with response analytics",
    [
        "to create survey with data:",
        "    set data.id to generate_id()",
        "    set data.created_at to now()",
        "    set data.responses to []",
        '    set surveys to load("surveys.json")',
        "    add data to surveys",
        '    save surveys to "surveys.json"',
        "    respond with data",
        "",
        "to get survey with id:",
        '    set survey to load("surveys.json", id)',
        "    respond with survey",
        "",
        "to submit response with survey_id and answers:",
        "    set response to {\"id\": generate_id(), \"survey_id\": survey_id, \"answers\": answers, \"submitted_at\": now()}",
        '    set responses to load("responses.json")',
        "    add response to responses",
        '    save responses to "responses.json"',
        "    respond with response",
        "",
        "to get analytics with survey_id:",
        '    set responses to load("responses.json")',
        "    set survey_responses to filter(responses, \"survey_id\", survey_id)",
        "    set total to length(survey_responses)",
        "    respond with {\"total\": total, \"responses\": survey_responses}",
        "",
    ],
    ["POST /surveys runs create_survey", "GET /surveys/:id runs get_survey",
     "POST /surveys/:id/respond runs submit_response", "GET /surveys/:id/analytics runs get_analytics"],
    [
        'section "surveys":',
        '    heading "Surveys"',
        '    button "Create Survey" action "createSurvey" style primary',
        '',
        'section "survey-form":',
        '    form action "/surveys/:id/respond" method POST:',
        '        list as questions:',
        '            card:',
        '                heading questions.text',
        '                list questions.options as option:',
        '                    input type radio name questions.id value option',
        '                    text option',
        '        button "Submit" type submit style primary',
        '',
        'section "results":',
        '    heading "Survey Results"',
        '    text from "/surveys/:id/analytics" as data: data.total " responses"',
    ],
    [
        'to generate questions with topic:',
        '    ask AI to "Generate 10 survey questions about: {{topic}}" save as questions',
        '    respond with {"questions": questions}',
        '',
        'to analyze responses with responses:',
        '    ask AI to "Analyze these survey responses and provide key insights: {{responses}}" save as insights',
        '    respond with {"insights": insights}',
        '',
    ],
)


# ── 20. Monitoring / Health Check ────────────
add(
    "monitoring",
    "a service monitoring and health check system with alerting",
    [
        "to add service with data:",
        "    set data.id to generate_id()",
        '    set data.status to "unknown"',
        "    set data.registered_at to now()",
        '    set services to load("monitored_services.json")',
        "    add data to services",
        '    save services to "monitored_services.json"',
        "    respond with data",
        "",
        "to check all services:",
        '    set services to load("monitored_services.json")',
        "    set results to []",
        "    repeat for each service in services:",
        "        set health to ping(service.url)",
        "        set service.status to health.ok ? \"up\" : \"down\"",
        "        set service.last_checked to now()",
        "        set service.latency to health.latency",
        "        add service to results",
        '    save services to "monitored_services.json"',
        "    respond with results",
        "",
        "to get service status with id:",
        '    set services to load("monitored_services.json")',
        "    set service to find_by(services, \"id\", id)",
        "    respond with service",
        "",
        "to list down services:",
        '    set services to load("monitored_services.json")',
        "    set down to filter(services, \"status\", \"down\")",
        "    respond with down",
        "",
    ],
    ["POST /services runs add_service", "GET /services/check runs check_all_services",
     "GET /services/:id runs get_service_status", "GET /services/alerts/down runs list_down_services"],
    [
        'section "monitoring":',
        '    heading "Service Monitoring"',
        '    button "Check All" action "checkAll" style primary',
        '',
        '    grid columns 3:',
        '        card:',
        '            heading "Total Services"',
        '            text from "/services" as s: s.length',
        '        card:',
        '            heading "Up"',
        '            text style success',
        '        card:',
        '            heading "Down"',
        '            text style danger',
        '',
        '    list from "/services" as services:',
        '        card:',
        '            heading services.name',
        '            text services.url style mono',
        '            badge services.status "up" "down"',
        '            text services.latency style meta',
        '            text services.last_checked style meta',
    ],
    [
        'to diagnose outage with service:',
        '    ask AI to "Diagnose this service outage and suggest fixes: {{service.name}} at {{service.url}} — error: {{service.error}}" save as diagnosis',
        '    respond with {"diagnosis": diagnosis}',
        '',
        'to generate incident report with services:',
        '    ask AI to "Write an incident report for these down services: {{services}}" save as report',
        '    respond with {"report": report}',
        '',
    ],
)


# ─────────────────────────────────────────────
#  Write output files
# ─────────────────────────────────────────────

def write_projects():
    os.makedirs(OUT_DIR, exist_ok=True)

    count = 0
    for p in PROJECTS:
        content = project(
            p["name"],
            p["description"],
            p["back_behaviors"],
            p["back_routes"],
            p["front_sections"],
            p["agent_behaviors"],
            p["features"],
            p["theme_lines"],
        )
        filename = f"{slug(p['name'])}_full_app.nc"
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        count += 1
        print(f"  OK {filename}")

    # Generate variations (with/without auth, different themes, simplified)
    for p in PROJECTS[:10]:  # first 10 get variations
        # Variation: API-only (no frontend)
        simple_name = p["name"] + "-api"
        lines = [
            f"<|begin|>",
            f"// Description: {p['description']} (API only, no frontend)",
            f"// Type: service",
            f'service "{slug(simple_name)}"',
            f'version "1.0.0"',
            "",
        ]
        lines += p["back_behaviors"]
        lines += ["api:"] + [f"    {r}" for r in p["back_routes"]]
        lines += ["    GET /health runs health_check", ""]
        lines += ["to health check:", f'    respond with {{"status": "ok"}}']
        lines += ["<|end|>", ""]
        filename = f"{slug(p['name'])}_api_service.nc"
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
        count += 1
        print(f"  OK {filename}  (api-only variation)")

    print(f"\n  Total: {count} training files written to:\n  {OUT_DIR}\n")
    print("  Next step — train the model:")
    print(f"  nc train --data {OUT_DIR} --dim 512 --layers 8 --epochs 50")


if __name__ == "__main__":
    write_projects()
