// Todo Service — generated by NC AI
// Prompt: "todo app with tasks and categories"

service "todo-api"
version "1.0.0"

// â”€â”€ Todo CRUD â”€â”€â”€

to list_todos:
    gather items from "todos"
    respond with items

to get_todo with id:
    gather item from "todos" where id is id
    if item is empty:
        respond with error "Todo not found"
    respond with item

to create_todo with data:
    set data.id to generate_id()
    set data.created_at to now()
    set data.updated_at to now()
    store data into "todos"
    log "Created todo: " + data.id
    respond with data

to update_todo with id and data:
    set data.id to id
    set data.updated_at to now()
    store data into "todos"
    respond with data

to delete_todo with id:
    gather existing from "todos" where id is id
    if existing is empty:
        respond with error "Todo not found"
    gather todos_list from "todos"
    remove existing from todos_list
    store todos_list into "todos"
    respond with {"deleted": id}

to health_check:
    respond with {"status": "healthy", "service": "todo-api"}

// â”€â”€ Routes â”€â”€â”€

middleware:
    use cors
    use log_requests

api:
    GET  /todos              runs list_todos
    GET  /todos/:id           runs get_todo
    POST /todos              runs create_todo
    PUT  /todos/:id           runs update_todo
    DELETE /todos/:id         runs delete_todo
    GET  /health             runs health_check
