// Todo Tests â€” generated by NC AI

to test_create_todo:
    set data to {"name": "Test Todo", "description": "Test item"}
    set result to create_todo(data)
    assert result.id is not empty, "Should have ID"
    assert result.name is equal "Test Todo", "Name should match"
    respond with "ok"

to test_list_todos:
    set items to list_todos()
    assert type(items) is equal "list", "Should return list"
    respond with "ok"

to test_health_check:
    set result to health_check()
    assert result.status is equal "healthy", "Should be healthy"
    respond with "ok"

